using System;
using Unity.Entities;

namespace Ecosystem.ECS.Animal
{
    /// <summary>
    /// Represents the exact age of death for an entity. This component is generated by the AgeOfDeathSystem.
    /// </summary>
    [Serializable]
    public struct AgeOfDeathData : IComponentData
    {
        public float Value;
    }
}
